## Hypothesis Testing

### Hypothesis Testing 1

In [43]:
import pandas as pd
from scipy import stats as stats
import numpy as np

In [34]:
Cutlets=pd.read_csv("Cutlets.csv")
Cutlets.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [35]:
UnitA = Cutlets['Unit A']
UnitB = Cutlets['Unit B']

In [37]:
pvalue = stats.ttest_ind(UnitA,UnitB)[1]
pvalue

0.4722394724599501

In [38]:
if pvalue < 0.05:
    print('Rejct null hypothesis')
else:
    print('Fail to reject null hypothesis')

Fail to reject null hypothesis


### Hypothesis Testing 2

In [39]:
Lab = pd.read_csv('LabTAT.csv')
Lab.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [40]:
Lab1=Lab['Laboratory 1']
Lab2=Lab['Laboratory 2']
Lab3=Lab['Laboratory 3']
Lab4=Lab['Laboratory 4']

In [41]:
pvalue = stats.f_oneway(Lab1,Lab2,Lab3,Lab4)[1]
pvalue

2.1156708949992414e-57

In [42]:
if pvalue < 0.05:
    print('Rejct null hypothesis')
else:
    print('Fail to reject null hypothesis')

Rejct null hypothesis


### Hypothesis Testing 3

In [3]:
df= pd.read_csv('BuyerRatio.csv')
df.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [4]:
df_new=df.iloc[:,1:6]
df_new

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [5]:
df_new.values

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]], dtype=int64)

In [7]:
val=stats.chi2_contingency(df_new)
val

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [8]:
no_of_rows=len(df_new.iloc[0:2,0])
no_of_columns=len(df_new.iloc[0,0:4])
degree_of_f=(no_of_rows-1)*(no_of_columns-1)
print('Degree of Freedom=',degree_of_f)

Degree of Freedom= 3


In [9]:
Expected_value=val[3]

In [10]:
Expected_value

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [12]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2/e for o,e in zip(df_new.values,Expected_value)])
chi_square_statestic=chi_square[0]+chi_square[1]
chi_square_statestic

1.5152956451130446

In [14]:
critical_value=chi2.ppf(0.95,3)
critical_value

7.814727903251179

In [16]:
if chi_square_statestic >= critical_value:
    print('Dependent (reject H0)')
else:
    print('Independent (fail to reject H0)')

Independent (fail to reject H0)


In [17]:
pvalue=1-chi2.cdf(chi_square_statestic,3)
pvalue

0.6787446296467897

In [18]:
if pvalue <= 0.05:
     print('reject H0')
else:
     print('fail to reject H0')

fail to reject H0


### Hypothesis Testing 4

In [19]:
import pandas as pd
from scipy import stats as stats
from scipy.stats import chi2_contingency
from scipy.stats import chi2

In [21]:
df= pd.read_csv('Costomer+OrderForm.csv')
df

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [23]:
print(df['Phillippines'].value_counts(),df['Indonesia'].value_counts(),df['Malta'].value_counts(),df['India'].value_counts())

Error Free    271
Defective      29
Name: Phillippines, dtype: int64 Error Free    267
Defective      33
Name: Indonesia, dtype: int64 Error Free    269
Defective      31
Name: Malta, dtype: int64 Error Free    280
Defective      20
Name: India, dtype: int64


In [24]:
obs=([[271,267,269,280],[29,33,31,20]])
obs

[[271, 267, 269, 280], [29, 33, 31, 20]]

In [25]:
stat, p, dof, expected = chi2_contingency([[271,267,269,280],[29,33,31,20]])

In [26]:

stat

3.858960685820355

In [27]:
p

0.2771020991233135

In [28]:
dof

3

In [29]:
expected

array([[271.75, 271.75, 271.75, 271.75],
       [ 28.25,  28.25,  28.25,  28.25]])

In [30]:
print('dof=%d' % dof)
print(expected)

dof=3
[[271.75 271.75 271.75 271.75]
 [ 28.25  28.25  28.25  28.25]]


In [31]:
alpha = 0.05
prob=1-alpha
critical = chi2.ppf(prob, dof)
print('probability=%.3f, critical=%.3f, stat=%.3f' % (prob, critical, stat))
if abs(stat) >= critical:
    print(' reject H0,variables are related')
else:
    print('fail to reject H0, variables are not related')

probability=0.950, critical=7.815, stat=3.859
fail to reject H0, variables are not related


In [32]:
print('significance=%.3f, p=%.3f' % (alpha, p))
if p <= alpha:
    print('Dependent (reject H0)')
else:
    print('Independent (fail to reject H0)')

significance=0.050, p=0.277
Independent (fail to reject H0)
